############################
# Dockerfile image         #
# nginx + fpm 7.3
#
#
############################
# Base image-nya Ubuntu
FROM ubuntu:18.04
# Author: Muhammad Cordiaz
MAINTAINER Muhammad Cordiaz <cordiaz@cordiaz.com>
# Install apache2 package
RUN apt-get update
RUN apt-get install -y nginx
RUN apt install software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt update
RUN apt install php7.3 php7.3-fpm
COPY default /etc/nginx/sites-avaiable/example.com
RUN apt-get clean
